'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9179
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CircusPals.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AboutBanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutBanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aboutboxnewprototypr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aboutboxnewprototypr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property agent_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agent_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property agent_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agent_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property almost_invisible_max() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almost_invisible_max", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property almost_invisible_max1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almost_invisible_max1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property almost_invisible_max2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almost_invisible_max2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property amazingfact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("amazingfact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Animate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Animate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Audio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BackgroundWatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bonkeyupdate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bonkeyupdate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bonzibg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bonzibg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CaineBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CaineBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CaineShare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CaineShare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property circus_pals_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("circus_pals_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CircusBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CircusBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CircusBit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CircusBit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property circuspals_firsttime() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("circuspals_firsttime", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property CircusUpdate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CircusUpdate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CompUpdate2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CompUpdate2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computerbg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computerbg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cosmicbutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cosmicbutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cosmiclogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cosmiclogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cosmiclogo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cosmiclogo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property darkbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darkbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DialogBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DialogBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property game_candy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_candy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property game_gloinks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_gloinks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property game_haunt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_haunt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property game_spud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_spud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Games() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Games", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GameScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GameScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gestureright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gestureright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gestureright2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gestureright2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hostedon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hostedon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Joke() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Joke", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jordon_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jordon_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JungleThemeNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JungleThemeNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lazer98() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lazer98", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lb_bluebg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lb_bluebg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lightbluebg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightbluebg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lightbluebg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightbluebg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property listening() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listening", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MASH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MASH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mashbutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mashbutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maxalert_rewritten_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxalert_rewritten_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maxalertbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxalertbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maxalerttransparentbgfixed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxalerttransparentbgfixed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moveright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moveright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mushbutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushbutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property panelbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panelbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property panelbg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panelbg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pleased() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pleased", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property runmsh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runmsh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property runmsh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runmsh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SingOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SingOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SingOff1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SingOff1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SingOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SingOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SingOn1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SingOn1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Speak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Speak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property speak1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speak1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SplashScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplashScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stop2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Surf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Surf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tabcontrolhider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tabcontrolhider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tabcontrolhider2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tabcontrolhider2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tabcontrolmodulejungle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tabcontrolmodulejungle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updatebutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updatebutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updatebuttonwithbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updatebuttonwithbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
